name: TEST CRON
  
on:
  workflow_dispatch:  # تشغيل يدوي
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test run
        run: echo "✅ CRON WORKS - $(date)"
